# version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./requirements/.env
    networks:
      - backend
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_v:/var/lib/html
    env_file:
      - ./requirements/.env
    depends_on:
      - mariadb
    networks:
      - backend
    restart: always

volumes:
  mariadb_v:
    driver: local
    driver_opts:
        device: /home/bde-wits/data/maria
        type: none
        o: bind
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/suliak/data/wordpress
      o: bind

networks:
  backend:
    driver: bridge