# version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./requirements/.env
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_v:/var/lib/html
    env_file:
      - ./requirements/.env
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - nginx:/var/www/html
    env_file: ./requirements/.env
    depends_on:         # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
      - wordpress
#   dockerfile: Dockerfile
    ports:
      - "443:443" # on indique le port qui sera exposé a la machine locale
    networks:
      - backend
    restart: on-failure 		# Ici nous changeons, le container redémarrera uniquement en cas de crash.

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      device: /home/bde-wits/data/maria
      # device: /home/suliak/data/maria
      type: none
      o: bind
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/bde-wits/data/wordpress
      # device: /home/suliak/data/wordpress
      o: bind
  nginx:
    driver: local
    driver_opts:
      type: none
      device: /home/bde-wits/data/nginx
      o: bind

networks:
  backend:
    driver: bridge