# version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./requirements/.env
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_v:/var/lib/html
    env_file:
      - ./requirements/.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend
    restart: always

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${PWD}/database
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      # device: /home/bde-wits/data/wordpress
      device: ${PWD}/wordpress
      o: bind

networks:
  backend:
    driver: bridge