version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./requirements/.env
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_v:/var/www/wordpress
    env_file:
      - ./requirements/.env
    depends_on:
      mariadb:
        condition: service_healthy
    # On SUPPRIME la ligne ports: [ "9000:9000" ] pour empêcher l'exposition en externe
    networks:
      - backend
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_v:/var/www/html
    env_file: ./requirements/.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - backend
    restart: on-failure

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      device: /home/bde-wits/data/maria
      type: none
      o: bind
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/bde-wits/data/wordpress
      o: bind

networks:
  backend:
    driver: bridge
