FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y nginx openssl curl && \
    apt-get clean

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -out /etc/nginx/ssl/inception.crt \
    -keyout /etc/nginx/ssl/inception.key \
    -subj "/C=FR/ST=Occitanie/L=Perpignan/O=42/OU=42/CN=bde-wits.42.fr"

RUN mkdir -p /run/nginx

COPY ./conf/nginx.conf /etc/nginx/conf.d

RUN mkdir -p /var/www/html
RUN chmod 755 /var/www/html && chown -R www-data:www-data /var/www/html

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]